# Generated by Django 5.1.8 on 2025-12-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oauthaccount',
            unique_together={('provider', 'id')},
        ),
        migrations.RemoveField(
            model_name='oauthaccount',
            name='uid',
        ),
    ]
